### ISSUE TITLE
Logo in Plone 3 theme

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#25]
make use of the old logo in the Theme for version 3

**Comment by svx** [comment]
@loechel do we still have the old logo somewhere ?

**Comment by loechel** [comment]
fixed with 7bcca8989dff326a2cd895a9e9ea6725b8628385

see https://github.com/plone/sphinx.themes.plone/blob/master/src/sphinx/themes/plone/plone_basic/static/img/plone-classic.jpg
