### ISSUE TITLE
The version switcher needs extra select

### ISSUE THREAD

**Issue by polyester** [plone/sphinx.themes.plone#28]
The version-switcher at sphinx.themes.plone/src/sphinx/themes/plone/plone_basic/static/js/version_switch.js_t currently supposes the URL pattern is always the same, namely
http://docs.plone.org/version/language/restofurl

that is the case for the 3 and 5 docs; but for the current canonical version we strip out the 4/en part of the url, 
so http://docs.plone.org/4/en/quickstart/index.html becomes http://docs.plone.org/quickstart/index.html

This makes the select work correctly in the direction 3 => 4, but not 4 => 3

So: the version checker should
- check if current URL starts with [345], if so, use the current patch_url function
- if not, insert /4/en into current URL, then hand over to patch_url

**Comment by loechel** [comment]
@svx I have done some updates on the version switcher idea: see f0630068b5e331dd2419d2cf08b4056f78fee4b0

Please test and then say if that is enough or needs more work.

the conf.py in the docs needs 


    'version_switcher': True,
    'always_show_version_switcher': True,
    'language_switcher': False,
    'always_show_language_switcher': False,

set in the html_theme_options.

**Comment by svx** [comment]
@polyester would you mind to check, you were working on that, right ?

**Comment by polyester** [comment]
testing (with vagrant: https://github.com/leftxs/vagrant.docs.plone.org) it is not working, I'm getting a 

ReferenceError: assignment to undeclared variable current_version

and the same (once I put in an empty declaration like)
```javascript
    var current_version;
```
happens with current_language and a_length

Even after adding those two also as empty var declarations, I fail to see how

```javascript
        if (path.length > 2) {
            current_version = path[1];
            if (DOCUMENTATION_OPTIONS.USE_VERSION_SWITCHER && in_array(current_version, DOCUMENTATION_OPTIONS.VERSIONS)) {
                path[1] = version;
            }
            if (DOCUMENTATION_OPTIONS.USE_LANGUAGE_SWITCHER && in_array(current_language, DOCUMENTATION_OPTIONS.LANGUAGES)) {
                if (DOCUMENTATION_OPTIONS.USE_VERSION_SWITCHER && in_array(current_version, DOCUMENTATION_OPTIONS.VERSIONS)) {
                    path[1] = lang;
                }
                else {
                    path[2] = lang;
                }
            }
```

is ever going to work, since 'path' will either
-  be something like "docs.plone.org/manage/deploying/index.html", in which case the code will bork (I think)
- be something like "docs.plone.org" in which case nothing happen.

so I think this only works **back** from version 3, where the URL is docs.plone.org/3/en/whatever, but not for the case where we are on 4/en, but the 4/en is not present in the path. (And that's also what I can observe from testing)

**Comment by svx** [comment]
@polyester did you also changed the nginx config of the sites, the new version switcher is suposed to asume  the urls diferent:
"Additionally It assumes that the url is always the same structure schema://host/[version]/[language]/path... so docs.plone.org has to be like docs.python.org always show and redirect to current version on root path / --> docs.plone.org/ docs.plone.org/4/ or docs.plone.org/4.3/"

Which would mean we have to change the site configs in nginx, right ?

As example is docs.python.org mentioned

**Comment by polyester** [comment]
ah no, I didn't. 

But that needs some more thinking: 
- has implications for SEO, and for links currently out there
- rewrites get a bit complicated

I would rather fix it in the javascript; all that would be needed there is just to insert a string into the "path" array if it isn't there. I'll google for how to do that in JS ;-)

**Comment by svx** [comment]
Yes, I know, we should sit down and re-think, there are some valid reasons behind the idea of breaking out current setup.
So yes we shoud sit down with some liquid and talk about that including all cons and pros and see where this goes.
This is mentioned now, because we thought **if** we want do that we plan in advance and be careful so Plone 5 release would be a possility.
Please all of you note the big **if** there is **no** decision made, it *just* an idea which needs to be discussed ...

**Comment by polyester** [comment]
for now solved the problem with a 'normalize_url' function
