### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#29]
@loechel I would like to make a 0.2 release, soon, this time also as an egg and as wheel, should I wait till we[you] :) fixed the JavaScript issue ?

**Comment by loechel** [comment]
@svx please wait till i get the JavaScript in. I will work on this this weekend. I will notfiy you here if you could cut the release.

**Comment by svx** [comment]
:+1:

**Comment by loechel** [comment]
is still pending on #28 if that works make a release, if not notify me.

**Comment by svx** [comment]
closing this
