### ISSUE TITLE
Add feedback button 

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#30]
Would it make sense to add a feedback, button ? Lots of other docs have this, we could add one too, which opens mail or opens a link to community.plone.org.

Mostly this is done via JavaScript, for example this how it looks like on the drone docs.
![feedback](https://cloud.githubusercontent.com/assets/358860/8304417/e31058ea-19a5-11e5-9baf-4a77bcf65856.png)
 
@loechel would it be possible to include something like that ?

**Comment by loechel** [comment]
Well, Feedback make always sense. The question is how we want to solve it. I have at least 3 ideas:

* static Feedback form in the theme
* XSS Form via JavaScript
* Inculding community.plone.org

all three are possible. we should have a short discussion on that.

**Comment by svx** [comment]
I would tend to the from via JavaScript, what we connect in the back [mail or community or something else should not matter]

**Comment by svx** [comment]
@loechel I started to implement that in: https://github.com/plone/sphinx.themes.plone/tree/svx_fresh

Would you mind to check ? Does it makes sense in that way ?

Mu idea is that is should be possible to configure it through a setting [true or false] in conf.py

**Comment by svx** [comment]
@loechel ping !

**Comment by loechel** [comment]
Sorry have been on business travel will be looking this weekend.

**Comment by loechel** [comment]
Well I did add some comments on the code: https://github.com/plone/sphinx.themes.plone/commit/dbb921e511f2c702f95a49258dcc5a1676638794 hope that is enough feed back, if you fix that please make a pull reqiuest and I will look again.
