### ISSUE TITLE
Add link to site

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#31]
from @tkimnguyen:

add to the template a link to the issue tracker on each page with the label being "Report a problem"

@tkimnguyen can you please evaluate a bit more ?

- Do you mean a link in the link section [footer] or where ?
- What do you mean with 'on each page' ? 
- Do you have a mockup ?

**Comment by tkimnguyen** [comment]
thx @svx - I'm not sure where it would make the most sense to put the link or button; ideally in more than one place unless it's one of those neat UI things that follows you as you scroll up/down the page. I meant on each page of the documentation so that whenever someone sees a problem with the docs (e.g. broken link, or typo) they just click on the "Report a Problem" button and it automatically includes in the form the URL, asks for name / email / github account (maybe prepopulates these values if the person is logged into GitHub), and a text area where the person can describe the issue more. No, sorry, I don't have a mockup.

**Comment by svx** [comment]
So maybe we could combine that with: https://github.com/plone/sphinx.themes.plone/issues/30 ?

And add two things, like feedback and report ?

**Comment by davilima6** [comment]
If not two things, three. :-)

Old Developer Docs had a direct `Edit this page` link which I think would be great for increasing contributions, especially for first-timers. Then there could be this other link to "Give feedback/Report errors". IMO that could be just one link to new issue on the repo, with current page's URL pre-filled in title or body fields.

**Comment by tkimnguyen** [comment]
Might be good to keep the issues separate, because #30 looks like it's about the implementation of the button or link. This issue could be what the button or link actually does. 

I don't think we should add two or three things... if the point is to keep things simple especially for people who have limited tolerance for complexity (ie. not Plone hardcore devs!).

Even an "Edit this Page" might be too much since it would require learning some markdown... If we want to encourage helpful suggestions, I think it's best to leave it as freeform as possible.

**Comment by tkimnguyen** [comment]
oops sorry! dang tab order!

**Comment by svx** [comment]
@davilima6 How would you handle http://docs.plone.org/about/contributing.html#workflow then ?

**Comment by svx** [comment]
@tkimnguyen I am a bit concerned, :) IMHO a form or a simple link to github is not enough, people who are less technical will just get frustrated if they see a github issue tracker :)

The same goes for a form asking for a github account, this is certainly a awesome feature for people who already know all this stuff, but less cool for someone who is reading 'working with content' and sees something what can be improved, but this person never heard about github and all this technical terms at all :)

We could create a new static template explaining all this and have a link to github in this template or we could link straight to http://docs.plone.org/about/contributing.html.

Personally I am all in for improve all this and make it easier, I am plus +10000 on this, if we would have money I would go for something like https://usersnap.com/ which you can connect to your github repository and then you have a nice setup for technical and also less technical user.

But unfortunately we do not have the money to do that :( - :)

On a site note, this has now nothing to do with this ticket :) :
IMHO we still have the 'challenge' to think about something what works for everyone and not only for 'github user' :)

**Comment by davilima6** [comment]
@svx you mean the fact that contributions need to be made through PRs? Imo that's exactly where 2 action buttons would come in handy: we have 2 audiences to promote contributions from.

For the non-technical/outsiders we can provide a "Give feedback" button that slides in sth like [GetSatisfaction](https://getsatisfaction.com/) or Usersnap. Inside of it you choose if you're reporting an error, suggesting raw non-Github-dirty-and-quick fixes for some paragraphs, or just sharing an idea - we also might display smileys. With a Captcha in place, one idea would be automatically creating an issue (from some robot account) so it's easier to triage: no new system and closer integration to the related content.

For the others, those who want to change wording right away, I think we should try and be confident that an "Edit this page" button won't break the way coredev/collective members already agree to work (PRs). Maybe we can have a small question mark icon with a tooltip on "How to contribute" to avoid a splash/disclaimer page, which would be boring for most who already began contributing. Or simply rely on the new "guidelines for contributing" @mauritsvanrees already put at work on https://github.com/plone/Products.CMFPlone/issues/new

Also we need to take into account this is a major release in which too many things changed and this time we don't have a print, single-handedly written book to spread trust around. I mean, we must really low barriers - even if we must revise and correct things a bit more - or risk continuing to have few writers.

**Comment by svx** [comment]
Well so basically seeing the big picture we are saying more or less the same :)

**Comment by tkimnguyen** [comment]
I didn't mean that the link or button should send anyone to Github. It should go to a form that we control and we keep the form very simple to the user. When they submit the form we decide what happens. There has to be a human making judgements about where to send the submitted data.

**Comment by tkimnguyen** [comment]
Ah I see originally that's what I was asking for (a link that takes people to the Github issue tracker). But that's only a short term and not very good solution if we want to draw in contributions from non traditional Plone devs and super techies. :)

**Comment by davilima6** [comment]
So.. do we a plan? :-)

**Comment by svx** [comment]
Don't know about consensus :), but I was looking into freshdesk.com, they have a free account, which is really basic but should be enough for us, and you can connect it to github: https://support.freshdesk.com/support/solutions/articles/214680

The limit is 20 repositories but we only need it for docs.plone.org and maybe plone.org and plone.com @tkimnguyen what do you think ?

If we think that could be a possible solution I will give it a try ! :)

**Comment by davilima6** [comment]
@svx: +1

**Comment by tkimnguyen** [comment]
Don't forget training docs... and we have quite a few "external" docs linked so would we want to cover those too? Might be confusing for people if we didn't cover everything.

**Comment by tkimnguyen** [comment]
Also wondering how this would fit with our existing "support framework" (what's listed on plone.org/support): stackoverflow, primarily.

**Comment by svx** [comment]
The idea is not to use the helpdesk or froum or what ever from freshdesk, the idea is to just use the feedback widget which is nice because you can use it for screen-shots, comments and so on and through freshdesk the widget can connect  to github and creates a new ticket, that is all ....
We do not want to use the rest of the functions ....

If you prefer you can also write you own js or whatever widget but this would be way more work :)

And further I should say we start small with one project and try it out, you do not want so use immediately on everything :)

BTW what do yo mean with 'external' docs ?

**Comment by tkimnguyen** [comment]
OK sounds good then! Let's do it :)

By external I meant things like http://docs.plone.org/external/plone.app.robotframework/docs/source/happy.html#require-plone-app-robotframework which seem to come from the package itself (in this case plone.app.robotframework, https://github.com/plone/plone.app.robotframework/tree/master/docs/source)

**Comment by loechel** [comment]
Hi, wouldn't something like Git Reports (https://gitreports.com/) not be a good idea, as it make github issues for each request, without the need for the reporter to have a github account.

The Widget is not the problem, that is what we would design.

**Comment by tkimnguyen** [comment]
That does look more like what we need here, though the "no need for a github account" is a two-edged sword.

**Comment by svx** [comment]
Hm .. do you actually had a look what do you can do with the widget from freshdesk ? Let me make clear, I do not want to advocate a certain service here, I do want something what is easy to use, easy to maintain and working :)

The git report thing is nice but IMHO *NOT* enough, with the widget from freshdesk for example the user get the possibility to add also full screen-shots or mark a part of the site and get this part as a screen-shot, and you can add comments to it.
You can also configure that widget to do much more, it just depends how crazy you want to be :).

Next, sure we could 'just' write out own widget, but taken how busy most of the ppl are already, who of us has the time and energy to do that and to be responsible for maintaining ?

Third point :) We also would get statistics ! I like them, because they help you actually to make your docs better !

@tkimnguyen about external docs, that does not matter, actually I do not understand why you thing that could be an issue.
I am talking here about docs.plone.org, everything what we have under /external is part of docs.plone.org.
If people would report there an issue on docs.plone.org/external/foo it would end up as a ticket under github.com/plone/documentation/issues.

That is exactly what people are doing now and then we push the issues to the certain project, that is also the intention, give ppl one place to report issues.
You can't assume that user know about all the different repos. :)

**Comment by tkimnguyen** [comment]
@svx ok let's do it - we can always change it later if it doesn't work out :)

**Comment by svx** [comment]
There you go: https://youtu.be/xcr7km7zSAg

**Comment by tkimnguyen** [comment]
Very nice!!! thx @svx :)

**Comment by svx** [comment]
closing this in favor of #30 

discussion is sill going on there :)
