### ISSUE TITLE
add an "in this section" checkbox to the search

### ISSUE THREAD

**Issue by tkimnguyen** [plone/sphinx.themes.plone#32]
originally filed in https://github.com/plone/documentation/issues/432

"so if I'm searching for 'gzip' in the Apache docs at http://docs.plone.org/manage/deploying/front-end/apache.html I don't get sent to (say) Diazo docs"

with @svx's reply: "Unfortunately that is not possible, I mean you can add the check-box, but the 'build in' search of sphinx which we are currently using is limited, you can define a search area but this is not working properly as least not deep in subdirs. There is a long standing open idea to hook up solr or elasticsearch which would give you way better results and also the possibility of filtering but no one had time to work on this yet."

**Comment by svx** [comment]
There is no solutions for this, so I close this for now, feel free to re-open, but well as I said there is no solution, yet.

We will get a better search 'soonish'  this hopefully will improve the search experience.
