### ISSUE TITLE
Change color of links or of 'note'

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#44]
![cant_see_link](https://cloud.githubusercontent.com/assets/358860/22551586/9857cdd4-e955-11e6-9abc-27af203db49c.png)

As we can see here, it is very hard to see that 'Customize Plone 5 default theme on the fly' is a link :)

**Comment by svx** [comment]
@polyester In terms of accessibility, are there certain colors which are more suited than others ?

**Comment by stevepiercy** [comment]
There is a spectrum of color blindness and other vision impairments. Higher contrast between foreground and background is usually more important than color choice, although red/green is the most common. Underline is recommended. Establishing a single dominant color for links is also recommended. I like WebAIM for quick summaries of the issues:
* Links and Hypertext: http://webaim.org/techniques/hypertext/
* Visual Disabilities: http://webaim.org/articles/visual/
* Nifty little tester: http://wave.webaim.org/

**Comment by polyester** [comment]
underline is good. I'd go for a very dark color here for the link, very deep aubergine for instance.

**Comment by svx** [comment]
Thanks all so far !

What would be smart to do ?
I would like to see the current situation improved asap and I would like to have consistency thought the whole docs.
Because of that I am not really sold on changing the css for links in boxes :), also because I suck in CSS and for sure in this related case.
If we change color of links we should do that through the whole docs.
This means we need to find a color setting which is more or less OK through/with our current theme and good in terms of accessibility.
I suck in colors, too. If you guys settle on a color and tell me a color-code I will change that in the theme.

We also should keep in mind that @polyester started already to work on a new theme, maybe it would be smarter to see what the status is and what is left to do, so that we can use it.

**Comment by stevepiercy** [comment]
If only there were an easy way to design a Sphinx theme! I've looked far and wide to find something as easy to use as webpack with automatic reloading and automatic Sphinx rendering, but have always come up empty handed.

The best option I came up with is to generate a small sample docs website with all possible elements rendered by Sphinx. Then design using webpack. Repeat the tedium. Here's the file I was using as part of Pyramid documentation:
https://github.com/Pylons/pyramid/blob/style-guide/docs/style-guide.rst

I've looked at other Sphinx themes for inspiration, too.
https://github.com/Pylons/pylons_sphinx_theme/wiki/New-Theme-Requests#example-themes

**Comment by polyester** [comment]
for now, we could change it to 

a:link, a:visited {
    color: #1b3471;
    text-decoration: underline;
}

at plone_basic.css line 147, 
but add 

.toctree-l1 a {
    text-decoration: none;
}

because the forest of underlines at the toctree would otherwise impede readability instead of helping it.

**Comment by svx** [comment]
@polyester done ! See https://github.com/plone/sphinx.themes.plone/pull/45

**Comment by svx** [comment]
Ok, did a build, we need to look carefully which css is in need of tweaks, we have now:
![link_need_more_tweak](https://cloud.githubusercontent.com/assets/358860/22787646/4dee2940-eedd-11e6-8c62-2aea208f0ec7.png)

Do we want header as links ? and so on ?

**Comment by svx** [comment]
Do we really want/need

```
.. contents:: :local:
```

This is causing most of this and also, we do not use it consistent through the docs, some we use and and most of the time we not use it ....

**Comment by svx** [comment]
Ok here screens with and without it.

IMHO without looks better and also do not shows 'double headers' 

![with_local](https://cloud.githubusercontent.com/assets/358860/22794271/e2e14aea-eef2-11e6-9aad-54f1a0b94a90.png)
![without](https://cloud.githubusercontent.com/assets/358860/22794300/fe53f96c-eef2-11e6-889f-1438958879ee.png)

**Comment by polyester** [comment]
+1 on without.

**Comment by svx** [comment]
OK I will prepare a PR for 5.0

I will do 5.1 tomorrow, or someone can try to cherry-pick

Lets start to remove this tag....

External also tomorrow coming ....

**Comment by svx** [comment]
PRs for 'external docs' are done:

https://github.com/plone/plone.api/pull/352
https://github.com/plone/plone.app.theming/pull/122

**Comment by svx** [comment]
ok done and pr's got merged, closing this :)
