### ISSUE TITLE
Replace 'feedback' with 'chat' (gitter) widget

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#47]
Should we replace the feedback (freshdesk) with the 'chat' (gitter) widget ?

Currently we use a 'feedback' widget, where ppl can ask questions and attach screen shots. The idea behind is is/was to get feedback/suggestions from user of docs.plone.org.

This is kind of working, but actually we never got 'feedback' we got questions about plone.

Would it be better to replace this with the gitter widget we already use on plone.org/training.plone.org ?

At least with this adjustment we would have some kind of consistency, cause on at least three sites we would have the same widget on the same spot.
Further points would be:

- less maintenance on docs
- ppl get connected to 'real time' help

@polyester, @tkimnguyen thoughts, ideas, comments ?

**Comment by tkimnguyen** [comment]
Sure, you could add the Open Chat (Gitter) button to docs.plone.org. Could you also leave the feedback widget but label it "Report a bug"?

Generally I'm at the point where I no longer want new people or questions coming to chat...

**Comment by svx** [comment]
@loechel since you are on fire :)

We have a branch: https://github.com/plone/sphinx.themes.plone/tree/add_gitter where I try to include the gitter widget, like we have it on plone.org and training.plone.org.
But I am too stupid, to get the CSS, right.

![screen-css-gitter-widget](https://cloud.githubusercontent.com/assets/358860/23553313/8df06d38-0020-11e7-839f-463e2e24f6c0.png)

As you can see in the picture the gitter widget is taking the CSS, from plone_basic, but for the widget I would like to have the link text 'OPEN CHAT' in white.

I tried various things with CSS to override it, but yeah I suck at CSS :)

If you have time and feel like it, would you mind to have a look sometime ?

:)

Thanks !

**Comment by loechel** [comment]
@svx no problem, will have a look tonight.

**Comment by tkimnguyen** [comment]
Merged! Thx all
