### ISSUE TITLE
Accessibility issues in header 

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#51]
Currently the HTML of our header is not conform to accessibility regulations, we should change that! HTML.

![title-tags-plone-docs](https://cloud.githubusercontent.com/assets/358860/24397650/3c14320c-13a7-11e7-9621-c86286777045.png)

Here the explanation for what ``title`` is used for and how:

https://www.w3.org/TR/WCAG20-TECHS/H33.html

**Comment by loechel** [comment]
I have already changed that, bt it never got live till now.

**Comment by gforcada** [comment]
Closing then.
