### ISSUE TITLE
CSS Issue with 5.1 theme

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#54]
There is a small CSS glitch on the new theme, the right top corner of the box to the left is showing the wrong colour 
![css-todo](https://cloud.githubusercontent.com/assets/358860/25384588/31390cba-29c1-11e7-8fa6-a781534abe3c.png)

Next to Introduction it is showing grey and not blue

**Comment by loechel** [comment]
@svx this is actually not a problem of the current theme, it is in all themes. There maybe with less color diff.

we do have a div#aside-toggle that was supposed to provide a similar functionallity as the sidebarbutton in https://docs.python.org/3/ or other sphinx themes, but actually never finalized. 

So what should happen now, remove it from all, hide it via css but actually keep it in the html dom

**Comment by loechel** [comment]
@svx any comments on that?

**Comment by svx** [comment]
If I am right the idea was to move somewhere in the future to a theme based on Alabaster ? @polyester ?

Putting that on the site, I would say we remove it, I do not see someone finishing that soon, so IMHO remove ! :)

@polyester thoughts ?

**Comment by loechel** [comment]
@svx & @polyester will discuss this tomorrow with Paul directly and do some work on it.
