### ISSUE TITLE
Matching colors

### ISSUE THREAD

**Issue by svx** [plone/sphinx.themes.plone#55]
Would it be an idea, to use the same color that we use for the 'menu' box on the left for the 'admonition' box ?

![match-colors](https://cloud.githubusercontent.com/assets/358860/26201486/865b45a4-3bd3-11e7-9bc1-2108217447c0.png)

Currently the 'admonition' box is a bit darker

**Comment by loechel** [comment]
we could do this, only for the new branch and design or all branches @svx ?
